ir_verbs = ["say", "said", "said", "make", "made", "made", "go", "went", "gone", "take", "took",
                  "taken", "come", "came", "come", "see", "saw", "seen", "know", "knew", "known", "get", "got",
                  "gotten", "give", "gave", "given", "find", "found", "found", "think", "thought", "thought", "tell",
                  "told",
                  "told", "become", "became", "become", "show", "showed", "shown", "leave", "left", "left", "feel",
                  "felt", "felt",
                  "put", "put", "put", "bring", "brought", "brought", "begin", "began", "begun", "keep", "kept", "kept",
                  "hold", "held", "held", "write", "wrote", "written", "stand", "stood", "stood", "hear", "heard",
                  "heard"
    , "let", "let", "let", "mean", "meant", "meant", "set", "set", "set", "meet", "met", "met", "run", "ran", "run",
                  "pay", "paid", "paid", "sit", "sat", "sat", "speak", "spoke", "spoken", "lie", "lay", "lain", "spend",
            "spent", "spent",
            "cut", "cut", "cut", "rise", "rose", "risen", "drive", "drove", "driven", "buy", "bought", "bought",
            "wear", "wore", "worn", "choose", "chose", "chosen", "arise", "arose", "arisen", "awake", "awoke",
            "awoken",
            "be", "was", "were", "been", "bear", "bore", "born", "beat", "beat", "beaten", "bend", "bent", "bent",
            "bite", "bit", "bitten", "bleed", "bled", "bled", "blow", "blew", "blown", "broadcast", "broadcast",
            "broadcast"
    , "build", "built", "built", "burn", "burnt", "burnt", "burst", "burst", "burst", "can", "could",
            "catch", "caught", "caught", "cling", "clung", "clung", "cost", "cost", "cost", "creep", "crept",
            "crept",
            "deal", "dealt", "dealt", "dig", "dug", "dug", "do", "did", "done", "dream", "dreamt", "dreamt",
            "drink", "drank", "drunk", "eat", "ate", "eaten", "feed", "fed", "fed", "fight", "fought", "fought",
            "fly", "flew", "flown", "forget", "forgot", "forgotten", "forgive", "forgave", "forgiven",
            "freeze", "froze", "frozen", "git", "got", "got", "grind", "ground", "ground", "grow", "grew",
            "grown",
            "hang", "hung", "hung", "have", "had", "had", "hide", "hid", "hidden", "hit", "hit", "hit", "hurt",
            "hurt", "hurt",
            "kneel", "knelt", "knelt", "learn", "learnt", "learnt", "lent", "lent", "lent", "light", "lighted",
            "lighted",
            "lose", "lost", "lost", "may", "might", "mow", "mowed", "mown", "must", "had to", "overtake",
            "overtook", "overtaken",
            "ride", "rode", "ridden", "ring", "rang", "rung", "saw", "sawed", "sawn", "sell", "sold", "sold",
            "send", "sent",
            "sent", "sew", "sewed", "sewn", "shake", "shook", "shaken", "shall", "should", "shed", "shed", "shed",
            "shine",
            "shone", "shone", "shoot", "shot", "shot", "shrink", "shrank", "shrunk", "shut", "shut", "shut",
            "sing", "sang",
            "sung", "sleep", "slept", "slept", "slide", "slid", "slid", "smell", "smelt", "smelt", "sow", "sowed",
            "sown",
            "spell", "spelt", "spelt", "spit", "spat", "spat", "spread", "spread", "spread", "steal", "stole",
            "stolen",
            "stick", "stuck", "stuck", "sting", "sang", "sung", "stink", "stank", "stunk", "strike", "struck",
            "swear", "swore", "sworn",
            "sweep", "ewept", "swept", "sweel", "swelled", "swollen", "swim", "swam", "swum", "swing", "swung",
            "swung",
            "teach", "taught", "taught", "tear", "tore", "torn", "throw", "threw", "thrown", "wake", "woke",
            "woken", "weep",
            "wept", "wept", "will", "would", "win", "won", "won", "wind", "wound", "wound"]
